const jsonData = [
    { "id": 'B23DCCN944', "name": 'Mai Đức Bình', "type": 'Bài tập', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '09/05/2022', 'detail': 1 },
    { "id": 'B20DCCN535', "name": 'Dương Tuấn Nam', "type": 'Kiểm tra thường xuyên', "exam_name": 'Lập trình Web', "date": '30/06/2021', 'detail': 1 },
    { "id": 'B20DCCN459', "name": 'Trần Đức Quân', "type": 'Giữa kỳ', "exam_name": 'Chủ nghĩa xã hội', "date": '24/06/2022', 'detail': 0 },
    { "id": 'B20DCCN797', "name": 'Mai Đức Bình', "type": 'Bài tập', "exam_name": 'Nhập Môn Trí Tuệ Nhân Tạo', "date": '15/12/2022', 'detail': 0 },
    { "id": 'B22DCCN164', "name": 'Đậu Quang Hiếu', "type": 'Giữa kỳ', "exam_name": 'Nhập Môn Trí Tuệ Nhân Tạo', "date": '20/02/2020', 'detail': 0 },
    { "id": 'B23DCCN170', "name": 'Mai Đức Bình', "type": 'Kết thúc học phần', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '31/05/2020', 'detail': 1 },
    { "id": 'B23DCCN382', "name": 'Lê Gia Huy', "type": 'Kiểm tra thường xuyên', "exam_name": 'Lập trình Web', "date": '16/03/2022', 'detail': 0 },
    { "id": 'B23DCCN994', "name": 'Mai Đức Bình', "type": 'Kết thúc học phần', "exam_name": 'Lập trình Web', "date": '13/12/2022', 'detail': 0 },
    { "id": 'B20DCCN353', "name": 'Trần Đức Quân', "type": 'Bài tập', "exam_name": 'Nhập môn công nghệ phần mềm', "date": '05/08/2022', 'detail': 1 },
    { "id": 'B22DCCN201', "name": 'Đậu Quang Hiếu', "type": 'Kiểm tra thường xuyên', "exam_name": 'Lập trình Web', "date": '29/10/2020', 'detail': 0 },
    { "id": 'B22DCCN864', "name": 'Dương Tuấn Nam', "type": 'Kiểm tra thường xuyên', "exam_name": 'Nhập Môn Trí Tuệ Nhân Tạo', "date": '11/10/2021', 'detail': 0 },
    { "id": 'B21DCCN257', "name": 'Tống Việt Hoàng', "type": 'Kết thúc học phần', "exam_name": 'Chủ nghĩa xã hội', "date": '17/10/2021', 'detail': 1 },
    { "id": 'B23DCCN124', "name": 'Trần Đức Quân', "type": 'Giữa kỳ', "exam_name": 'Cơ sở dữ liệu phân tán', "date": '15/11/2020', 'detail': 0 },
    { "id": 'B20DCCN010', "name": 'Tống Việt Hoàng', "type": 'Kết thúc học phần', "exam_name": 'Cơ sở dữ liệu phân tán', "date": '23/09/2020', 'detail': 0 },
    { "id": 'B22DCCN007', "name": 'Lê Gia Huy', "type": 'Kết thúc học phần', "exam_name": 'Nhập môn công nghệ phần mềm', "date": '05/05/2020', 'detail': 1 },
    { "id": 'B21DCCN071', "name": 'Đậu Quang Hiếu', "type": 'Giữa kỳ', "exam_name": 'Nhập môn công nghệ phần mềm', "date": '25/01/2021', 'detail': 1 },
    { "id": 'B21DCCN568', "name": 'Trần Đức Quân', "type": 'Giữa kỳ', "exam_name": 'Chủ nghĩa xã hội', "date": '06/01/2020', 'detail': 1 },
    { "id": 'B21DCCN105', "name": 'Đậu Quang Hiếu', "type": 'Bài tập', "exam_name": 'Chủ nghĩa xã hội', "date": '21/01/2020', 'detail': 0 },
    { "id": 'B23DCCN672', "name": 'Trần Đức Quân', "type": 'Giữa kỳ', "exam_name": 'Cơ sở dữ liệu phân tán', "date": '13/03/2022', 'detail': 0 },
    { "id": 'B22DCCN721', "name": 'Dương Tuấn Nam', "type": 'Giữa kỳ', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '29/03/2022', 'detail': 0 },
    { "id": 'B21DCCN336', "name": 'Trần Đức Quân', "type": 'Kiểm tra thường xuyên', "exam_name": 'Nhập Môn Trí Tuệ Nhân Tạo', "date": '01/12/2022', 'detail': 1 },
    { "id": 'B22DCCN370', "name": 'Đậu Quang Hiếu', "type": 'Giữa kỳ', "exam_name": 'Nhập môn công nghệ phần mềm', "date": '11/12/2020', 'detail': 0 },
    { "id": 'B21DCCN122', "name": 'Đậu Quang Hiếu', "type": 'Kết thúc học phần', "exam_name": 'Chủ nghĩa xã hội', "date": '07/11/2022', 'detail': 1 },
    { "id": 'B21DCCN213', "name": 'Trần Đức Quân', "type": 'Kết thúc học phần', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '11/03/2022', 'detail': 1 },
    { "id": 'B23DCCN150', "name": 'Đậu Quang Hiếu', "type": 'Kiểm tra thường xuyên', "exam_name": 'Chủ nghĩa xã hội', "date": '02/05/2021', 'detail': 0 },
    { "id": 'B23DCCN291', "name": 'Dương Tuấn Nam', "type": 'Giữa kỳ', "exam_name": 'Chủ nghĩa xã hội', "date": '02/07/2022', 'detail': 0 },
    { "id": 'B23DCCN651', "name": 'Trần Đức Quân', "type": 'Kết thúc học phần', "exam_name": 'Lập trình Web', "date": '10/09/2022', 'detail': 1 },
    { "id": 'B21DCCN283', "name": 'Mai Đức Bình', "type": 'Kết thúc học phần', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '10/07/2021', 'detail': 1 },
    { "id": 'B20DCCN059', "name": 'Mai Đức Bình', "type": 'Bài tập', "exam_name": 'Nhập Môn Trí Tuệ Nhân Tạo', "date": '10/10/2020', 'detail': 1 },
    { "id": 'B23DCCN313', "name": 'Tống Việt Hoàng', "type": 'Bài tập', "exam_name": 'Lập trình Web', "date": '10/03/2022', 'detail': 0 },
    { "id": 'B21DCCN477', "name": 'Trần Đức Quân', "type": 'Bài tập', "exam_name": 'Cơ sở dữ liệu phân tán', "date": '12/08/2020', 'detail': 1 },
    { "id": 'B21DCCN071', "name": 'Dương Tuấn Nam', "type": 'Bài tập', "exam_name": 'Lập trình Web', "date": '05/04/2022', 'detail': 0 },
    { "id": 'B20DCCN772', "name": 'Lê Gia Huy', "type": 'Bài tập', "exam_name": 'Cơ sở dữ liệu phân tán', "date": '29/09/2021', 'detail': 0 },
    { "id": 'B20DCCN989', "name": 'Tống Việt Hoàng', "type": 'Bài tập', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '28/01/2021', 'detail': 1 },
    { "id": 'B21DCCN438', "name": 'Trần Đức Quân', "type": 'Giữa kỳ', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '17/06/2020', 'detail': 1 },
    { "id": 'B23DCCN214', "name": 'Trần Đức Quân', "type": 'Bài tập', "exam_name": 'Nhập Môn Trí Tuệ Nhân Tạo', "date": '13/09/2020', 'detail': 1 },
    { "id": 'B21DCCN048', "name": 'Tống Việt Hoàng', "type": 'Giữa kỳ', "exam_name": 'Cơ sở dữ liệu phân tán', "date": '10/01/2022', 'detail': 0 },
    { "id": 'B23DCCN716', "name": 'Mai Đức Bình', "type": 'Bài tập', "exam_name": 'Lập trình Web', "date": '12/05/2020', 'detail': 1 },
    { "id": 'B21DCCN948', "name": 'Dương Tuấn Nam', "type": 'Kết thúc học phần', "exam_name": 'Chủ nghĩa xã hội', "date": '01/03/2020', 'detail': 1 },
    { "id": 'B22DCCN283', "name": 'Trần Đức Quân', "type": 'Bài tập', "exam_name": 'Cơ sở dữ liệu phân tán', "date": '24/11/2022', 'detail': 0 },
    { "id": 'B21DCCN623', "name": 'Dương Tuấn Nam', "type": 'Kết thúc học phần', "exam_name": 'Lập trình Web', "date": '19/12/2020', 'detail': 0 },
    { "id": 'B21DCCN781', "name": 'Dương Tuấn Nam', "type": 'Kiểm tra thường xuyên', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '22/01/2020', 'detail': 0 },
    { "id": 'B21DCCN324', "name": 'Trần Đức Quân', "type": 'Bài tập', "exam_name": 'Cơ sở dữ liệu phân tán', "date": '29/10/2022', 'detail': 1 },
    { "id": 'B21DCCN994', "name": 'Đậu Quang Hiếu', "type": 'Kết thúc học phần', "exam_name": 'Nhập Môn Trí Tuệ Nhân Tạo', "date": '24/07/2021', 'detail': 0 },
    { "id": 'B20DCCN518', "name": 'Trần Đức Quân', "type": 'Bài tập', "exam_name": 'Nhập môn công nghệ phần mềm', "date": '02/02/2022', 'detail': 1 },
    { "id": 'B22DCCN229', "name": 'Mai Đức Bình', "type": 'Bài tập', "exam_name": 'Lập trình Web', "date": '08/07/2020', 'detail': 1 }, ,
    { "id": 'B23DCCN619', "name": 'Dương Tuấn Nam', "type": 'Kiểm tra thường xuyên', "exam_name": 'Nhập Môn Trí Tuệ Nhân Tạo', "date": '29/07/2020', 'detail': 0 },
    { "id": 'B20DCCN201', "name": 'Mai Đức Bình', "type": 'Bài tập', "exam_name": 'Lập trình Web', "date": '06/08/2020', 'detail': 1 },
    { "id": 'B20DCCN389', "name": 'Lê Gia Huy', "type": 'Giữa kỳ', "exam_name": 'An Toàn Bảo Mật HTTT', "date": '30/12/2022', 'detail': 0 },
    { "id": 'B21DCCN488', "name": 'Tống Việt Hoàng', "type": 'Giữa kỳ', "exam_name": 'Lập trình Web', "date": '18/04/2021', 'detail': 0 }
]